language: ruby
dist: xenial

jdk:
  - openjdk8

addons:
  chrome: stable
  apt:
    packages:
    - ghostscript
    - graphicsmagick
    - imagemagick
    - libreoffice
    - poppler-utils
    - tesseract-ocr
    - libopenjp2-7
    - libopenjp2-tools
cache:
  bundler: true

before_install:
  - sudo apt-get update -q
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
  - sudo wget -P /opt/install https://brussels.lib.utah.edu/FITS/fits-1.4.1.zip
  - sudo unzip /opt/install/fits-1.4.1.zip -d /opt/install/fits-1.4.1
  - sudo chmod +x /opt/install/fits-1.4.1/*.sh
  - sudo ln -s /opt/install/fits-1.4.1/fits.sh /usr/local/bin/fits.sh
  - sudo wget -q -O /etc/ImageMagick-6/policy.xml https://raw.githubusercontent.com/samvera-labs/newspaper_works/master/config/vendor/imagemagick-6-policy.xml
  - sudo wget -q -O /opt/install/fits-1.4.1/xml/fits.xml https://raw.githubusercontent.com/samvera-labs/newspaper_works/82d0c18d1679696a762fd7083db83dac49de9b35/config/vendor/fits.xml
rvm:
  - 2.5.5

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    #- ENGINE_CART_RAILS_OPTIONS='--skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test'
  # Travis should check every minor version in a range of supported versions, because
  # rails does not follow sem-ver conventions, see http://guides.rubyonrails.org/maintenance_policy.html
  # It should be sufficient to test only the latest of the patch versions for a minor version, they
  # should be compatible across patch versions (only bug fixes are released in patch versions).
  matrix:
    - "RAILS_VERSION=5.1.7"

services:
  - redis
